apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: docker_secert 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-ip-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-ip
  template:
    metadata:
      labels:
        app: reverse-ip
    spec:
      containers:
      - name: simple-node-app
        image: readlg/testapp:2.0.1
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-ip-service
spec:
  selector:
    app: reverse-ip
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 80
  type: NodePort
