name: SecOps

on:
  push:
    branches:
      - secops
jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install gitleaks
        run: |
          curl -sSfL https://install.goreleaser.com/github.com/zricethezav/gitleaks.sh | sh -s -- -b $HOME/bin v7.4.0
          export PATH=$PATH:$HOME/bin

      - name: Run gitleaks
        run: |
          gitleaks --verbose --redact
