name: SecOps

on:
  push:
    branches:
      - secops
jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install git-secrets
        run: |
          curl -sSL https://raw.githubusercontent.com/git-secrets/git-secrets/master/install.sh | sudo bash
          sudo git-secrets --register-aws --register-gcp

      - name: Run git-secrets
        run: |
          sudo git-secrets --scan
