name: SecOps

on:
  push:
    branches:
      - secops
  pull_request:

jobs:
  Docker_build_scan_k8scan_DAST:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Build hyper app container
        run: |
          tag=$(grep -Eo '"version": "([^"]*)"' package.json | awk -F'"' '{print $4}')
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker build -t readlg/testapp:$tag .
          
      - name: Scan for Docker image vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v3
          #comment continue on error for prod usecase
        continue-on-error: true
        with:
          image: readlg/testapp:$tag
          severity_threshold: HIGH
          annotations: true  
          #uncomment timeout if scan fails because of db update
          #timeout: 10
      - name: push image to registry
        run: |
          docker push readlg/testapp:$tag

      - name: Scan Kubernetes Manifests
        uses: kubescape/github-action@main
        continue-on-error: true
        with:
          format: json
          outputFile: k8-scan-results.json
