name: SecOps

on:
  push:
    branches:
      - secops
  pull_request:

jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install detect-secrets
        run: |
          pip install detect-secrets

      - name: Run detect-secrets
        run: |
          result=$(detect-secrets scan)
          echo "$result"
          if [[ "$result" == *"hashed_secret"* ]]; then
            echo "Secret exposed. Exiting the build."
            exit 1
          fi
